### ISSUE TITLE
Publisher Configuration: Support Vendor Whitelist

### ISSUE THREAD

**Issue by hbruce27** [digi-trust/cmp#10]
Summary:
Some publishers (or advertisers) may only want to ask users for consent on behalf of a specific set of vendors (a subset of vendor ID's in the centralised vendor list). The CMP needs to support ingesting  a list of vendors that limit who consent is gathered for

Acceptance Criteria:
As a publisher, I should be able to upload a formatted list of vendors to serve as a whitelist
As a user, I should only see the whitelisted vendors in the CMP
As a user, if I "consent to all" in the CMP, I should only be consenting to the whitelisted companies

Details:
This can be a file alongside the configuration file

**Comment by anissaconnor** [comment]
Replaced with another ticket
