### ISSUE TITLE
Cmp reprompt even if is given full consent

### ISSUE THREAD

**Issue by DavideMoney** [digi-trust/cmp#108]
Using the following options:
```
repromptOptions: {
    fullConsentGiven: 360,
    someConsentGiven: 0,
    noConsentGiven: 0,
},
```

the cmp window continues to appear on following pageviewes even if full consent given.

**Comment by SupahNickie** [comment]
@DavideMoney , thank you for this bug report. We have a PR ready for review to handle this: https://github.com/digi-trust/cmp/pull/109 

After it goes through our code review process, we will release it shortly 👍

**Comment by DavideMoney** [comment]
@SupahNickie  ty 👍

**Comment by SupahNickie** [comment]
Fixed in https://github.com/digi-trust/cmp/releases/tag/v1.1.1
