### ISSUE TITLE
Publisher Configuration: Support Vendor Blacklist

### ISSUE THREAD

**Issue by hbruce27** [digi-trust/cmp#11]
Summary:
Some publishers (or advertisers) may want to limit the partners they are collecting user consent on behalf of. The CMP needs to support ingesting lists of vendors (subset of vendors in centralised list) that limit who consent is gathered for

Acceptance Criteria:
As a publisher, I should be able to upload a formatted list of vendors to serve as a blacklist
As a user, I should see all of the IAB vendors, less the blacklisted ones, in the CMP
As a user, if I "consent to all" in the CMP, I should only be consenting to all IAB vendors except those that have been blacklisted

Details:
This can be a file alongside the configuration file

**Comment by anissaconnor** [comment]
Captured in pubvendor.json tickets
