### ISSUE TITLE
mootools conflict

### ISSUE THREAD

**Issue by ciaoamigo** [digi-trust/cmp#111]
I have configured the plugin is installed. But you give me this error with mootools:
_"cmp.complete.bundle.js: 1 ERROR - (CMP) Failed to check user location. CMP not ready TypeError
Can not read property 'css' of undefined"_

How can I solve?
Thank you

**Comment by SupahNickie** [comment]
Hello @ciaoamigo , thanks for showing us your issue. Do you mind letting me know which page you have the CMP on to help diagnose?

Thanks.

**Comment by SupahNickie** [comment]
Going to close in a few days unless more information or steps to reproduce are provided.
