### ISSUE TITLE
css rules too wide are applied to whole site not only to the consent footer / modal

### ISSUE THREAD

**Issue by DavideMoney** [digi-trust/cmp#113]
As per subject with release 1.1.1 the css are applied to whole page, see attached image,
ex `<a>` tags became blue
![cattura](https://user-images.githubusercontent.com/39701809/41090532-c80c8a44-6a44-11e8-9a5a-a2e5267a8167.PNG)

**Comment by SupahNickie** [comment]
Thanks @DavideMoney for this report. This was a known issue in ticket https://github.com/digi-trust/cmp/issues/26 and we have a PR open to fix it here https://github.com/digi-trust/cmp/pull/112 .

However, at the time you reported this, this feature was in the unstable master branch, which is what we do our development work on. If you are using this CMP on a real live site, please use the release version of the bundle instead, which can be found at https://cdn.digitrust.mgr.consensu.org/1/cmp.complete.bundle.js or https://cdn.digitrust.mgr.consensu.org/1/cmp.bundle.js (depending on which installation you're going with). Thanks!
