### ISSUE TITLE
New Configuration Option: Thin Footer

### ISSUE THREAD

**Issue by hbruce27** [digi-trust/cmp#119]
Summary:
Some clients would like to call as little attention to the CMP as possible. In addition to moving the CMP to a footer message, they would like to lower its profile further by removing the "thanks for visiting" title

Acceptance criteria:
As a website owner, I should be able to configure the CMP to load as 'layout: "footer"|"modal"|"thin"' to switch between the newly released footer, the original modal, or a new, thinner footer

Details:
The logo should not render in the footer:"thin" case, even if one is specified
the "learn more" button should be moved down to be in line with the "Read more about access..." text
the "Accept and continue" button should stay where it is, in line with the "this site uses cookies..." text

**Comment by DavideMoney** [comment]
On our website [www.money.it](www.money.it) we changed the footer like this.

Desktop
![image](https://user-images.githubusercontent.com/39701809/41651381-bdd07c0c-7480-11e8-9496-beefb8f30b70.png)

Mobile
![image](https://user-images.githubusercontent.com/39701809/41651729-88d77f0e-7481-11e8-92ee-6d8ee1cbe28d.png)


With the current configuration the only problem is that upon a new release we need to change the css again.

It  could be really useful to have a css customization option similar to what you did in release 1.2.0

Thanks

**Comment by SupahNickie** [comment]
@DavideMoney The CSS configuration option will still apply here as well. Attached here is a preview screenshot for your review

<img width="1440" alt="screen shot 2018-06-20 at 7 42 52 am" src="https://user-images.githubusercontent.com/4782746/41665745-901058dc-745d-11e8-8a73-0a56b596aecf.png">

**Comment by DavideMoney** [comment]
@SupahNickie  In order to render as small as possible the footer layout, Is it possible to have an options to have the 2 buttons on the same line   as I showed in my previous message?

**Comment by SupahNickie** [comment]
@DavideMoney unfortunately we have already decided upon the standard layout for the "thin" layout. This is a new option however and you can continue to use the "footer" style layout that you already have if you like it the way it is without alteration.
