### ISSUE TITLE
Support for Different Browsers

### ISSUE THREAD

**Issue by hbruce27** [digi-trust/cmp#12]
Summary:
The CMP needs to be able to collect consent from users on different browsers

Acceptance Criteria:
As a publisher, I should expect that consent will be collected from the majority of users, regardless of their browser

Details:
For the time being, we would like to start by supporting the most popular browsers, and move down the list until we reach a 92% coverage rate (this may change with additional research)

**Comment by anissaconnor** [comment]
[browser_version-ww-monthly.xlsx](https://github.com/digi-trust/cmp/files/1938147/browser_version-ww-monthly.xlsx)

Attached shows market share by browser version world wide. Source: http://gs.statcounter.com/browser-version-market-share

Highlighted in yellow are browser versions that make up 90% market share.

**Comment by SupahNickie** [comment]
We'll make new issues as needed if we spot specific issues with compatibility

**Comment by anissaconnor** [comment]
Re-opening as need to leverage browser usage stats in the EU to influence automated browser testing
