### ISSUE TITLE
More specific targeting needed for consent form

### ISSUE THREAD

**Issue by povilaskascionis** [digi-trust/cmp#126]
Consent form styling is too unspecific. This adds risk affecting publisher's website. The example would be a proff.no front page where CMP adds a 15px margin to all <ul> elements with inline styling. This makes the top navbar pushed down from the top page.

**Comment by SupahNickie** [comment]
@povilaskascionis We have addressed this concern with PR https://github.com/digi-trust/cmp/pull/122 and it is released as of June 20. Please let us know if this does not fix your issue and I will close this ticket if it does. Thanks!

**Comment by povilaskascionis** [comment]
All is well. Thank you!
