### ISSUE TITLE
Implement Automated Browser Testing

### ISSUE THREAD

**Issue by anissaconnor** [digi-trust/cmp#129]
The working group has decided to prioritise automated browser testing in order to pick up on issues with our CMP operating in specific browsers that could effect publisher monetisation due to the CMP not operating correctly. Collectively we will agree on which browser we aim to support and which ones we do not. 

Next Steps include:

- Evaluate vendors that offer automated browser testing
- Get pipeline working between github and vendor so commits automatically executed. 
- Choose testing framework.
- Write browser test cases.
- Set up a process for reviewing, logging, prioritising and fixing errors.
- Establish costs associated with browser testing and figure out long term plan for handling costs
- Include testing of different configurations (e.g. layouts, global vs. local cookie setting)

**Comment by SupahNickie** [comment]
E2E testing now leverages multiple configurations in the `e2e` folder within the src/ directory. Any new files added to this directory have to be referenced in the webpack build configuration, but can then be used as routes for the browsers to hit.
