### ISSUE TITLE
Publisher Configuration: Support Group Consent

### ISSUE THREAD

**Issue by hbruce27** [digi-trust/cmp#13]
Summary:
Group consent is the ability of a private group of publishers to collect and share consent information among themselves

Acceptance Criteria:
As a publisher, I should be able to configure the CMP for group consent
As a publisher, I should be able to specify a domain where consent information is shared

Details:
If the user has disabled third party cookies or the browser does not support third party cookies, group consent should fallback to local consent

**Comment by SupahNickie** [comment]
Closed in https://github.com/digi-trust/cmp/pull/63
