### ISSUE TITLE
Support for WordPress Plugin

### ISSUE THREAD

**Issue by hbruce27** [digi-trust/cmp#136]
Summary:
Many of our long-tail publishers work with the free version of WordPress that does not allow JS. A plugin allows these publishers to install the CMP in their site and without having to write code.

Acceptance criteria:
v1
- Plugin is available to install in the WordPress Plugins marketplace
- Plugin needs to be able to be activated (using the activation hook) once installed
- Website owner should be able to toggle the CMP on or off 
-- Toggle should live on that users WP dashboard
-- This should toggle functionality of the entire tool (before any of the pop-up logic takes place)
- CMP should be configurable via JSON blob

v2
- All of the CMP configuration options are exposed to the user in the WP dashboard UI (no JS required for the end user) 

Details:
Per the WordPress documentation here https://developer.wordpress.org/plugins/the-basics/, it should be relatively straightforward to load the CMP on a WordPress page using a PHP WordPress plugin. Additional details on that here https://stackoverflow.com/questions/9141885/how-to-load-javascript-in-wordpress-plugin.

**Comment by dborzyaev** [comment]
Plugin settings UI requirements:
- UI should allow to change CMP setup in a safe, consistent and user-friendly way;
- Settings should be resettable to defaults easily;
- A set of config options should cause minimum questions and cover most of user configuration changes needs to minimise support.

- Configurable options:
    - Layout (default 'thin')
    - blockBrowsing (available only if layout is not 'modal’, default true for ‘modal’, false for other layouts)
    - forceLocale (default null)
    - gdprAppliesGlobally (default false)
    - storeConsentGlobally (default true)
    - logoUrl (default null)

![dt cmp wp plugin settings](https://user-images.githubusercontent.com/41348637/43407521-a57f4392-9427-11e8-8b63-f485ee63f8e9.png)

Open question: if we want to have two configuration modes, let's say 'Most commonly used options' and 'Customisation expert'.
I'd suggest to start with 1st mode and if no demand for additional customisation, leave it as is.

**Comment by ffeast** [comment]
As discussed offline, lets enable logo upload & removal via WP standard functionality
