### ISSUE TITLE
Support Group Consent as per spec

### ISSUE THREAD

**Issue by anissaconnor** [digi-trust/cmp#139]
CpEX publishers would like to capture and share consent for the way they (group of publishers) collectively process their users personal data and the way their collective list of vendors process personal data therefore would like to add support for Group consent (in addition to service specific and global consent that is supported already).

The vendor and publisher consent will need to be stored in a pre-defined domain that is accessible to all publishers. 

Vendor and Cookie format spec: https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/commit/a32574941ce201708e30e78702278efe1ce6cd59

CMP JS API spec: https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/CMP%20JS%20API%20v1.1%20Final.md

**Comment by SupahNickie** [comment]
This is actually already supported by the CMP. It does require a little bit of setup by the publisher, however.

First, they have to be able to host an HTML page on the domain that they wish to serve cookies on and allow cross domain requests from any origin on it. We can supply that as a small snippet that they would merely have to paste in and serve on their servers. Then, they would need to set the `globalConsentLocation` configuration option within the CMP to point to that HTML page.
