### ISSUE TITLE
CMP formatting displayed differently on various websites

### ISSUE THREAD

**Issue by lukascpex** [digi-trust/cmp#164]
The CMP UI is displayed differently on some of the tested websites, e.g. buttons not displayed correctly, different font sizes, changed alignment of the texts, changed or disappeared bullet points - see attached screenshots. I am also attaching the configuration file. The source code was taken from the master branch (last Friday 31/08).
**Tested sites**:
www.orbion.cz
www.ahaonline.cz
www.maminka.cz
**Browsers**: Chrome and Safari
**Note 1**: We had to take the CMP down from those sites, but you can still display it online on Chrome with a DTM Launch switch (stageing ON). 
**Note 2**: The variable PageviewCMP was added on our side for GA tracking.

![ahaonline - buttons](https://user-images.githubusercontent.com/40352396/45138910-60b99100-b1ae-11e8-8fb4-70671c5749d3.png)
![maminka - alignment](https://user-images.githubusercontent.com/40352396/45138911-61522780-b1ae-11e8-97e1-fc4b802743de.png)
![maminka - alignment 2](https://user-images.githubusercontent.com/40352396/45138912-61522780-b1ae-11e8-9798-eefa5f71dc1c.png)
![orbion - font and bullet points](https://user-images.githubusercontent.com/40352396/45138913-61522780-b1ae-11e8-9475-3e15206f442b.png)

**Comment by lukascpex** [comment]
[cmp-2018-09-05.js.txt](https://github.com/digi-trust/cmp/files/2365718/cmp-2018-09-05.js.txt)

**Comment by BetinaMansa** [comment]
Hi @lukascpex,
We cannot seem to recreate this issue. Can you please describe your actions in steps?
From the screenshots our developer states that there is only one logical conclusion: Website styles are overwriting CMP banner styles and thereby messes up the general display of the CMP banner. In order to confirm that, we need to actually see it on those websites, then we can point out the cause. If its CMP banner's problem - we fix it, if it is websites' global styles - they have to fix the site.

**Comment by lukascpex** [comment]
Hello,
sorry for the late reply, I was on a vacation and quite busy after that.
I can't put the CMP back on the websites live, now, but I have uploaded them in a debug mode. To see them, you would have to download the[ Adobe DTM switch](https://chrome.google.com/webstore/detail/launch-and-dtm-switch/nlgdemkdapolikbjimjajpmonpbpmipk?hl=en) plugin for Chrome. When the page loads and the plugin icon lights on, click on it and turn the debug and staging on. Then refresh the page and the CMP should display.

<img width="208" alt="screenshot 2018-11-02 at 09 25 31" src="https://user-images.githubusercontent.com/40352396/47903827-8698a480-de84-11e8-857e-394ad736f028.png">

I hope it'll help.
Cheers
Lukas

**Comment by BetinaMansa** [comment]
Hi again, 
We attempted to reproduce, but we simply cannot. I attached some screenshots to show you what we see. 
Perhaps you can provide us more details? Chrome version, etc.? Maybe something was updated in the meanwhile? 
Best, 
Betina
[CMP Screenshots.zip](https://github.com/digi-trust/cmp/files/2560939/CMP.Screenshots.zip)

**Comment by lukascpex** [comment]
Hi Betina,
our developer looked into it and made a fix, that we have put on the web this Tuesday, I think. It seems, it fixed the issue. Sorry, I forgot to tell you we have updated the version.

L.

**Comment by BetinaMansa** [comment]
Hello, 
No harm done, we are happy it works :) 
Best,
Betina
