### ISSUE TITLE
Multiple euconsent cookies on the same domain will break the cmp bundle.

### ISSUE THREAD

**Issue by pariz** [digi-trust/cmp#186]
Multiple euconsent cookies with different paths (one with path set on `/path/to/page` and the other set on root level `/`) will break the cmp bundle as it only expects one occurence of the cookie.

**Comment by samtingleff** [comment]
Thanks @pariz. Hoping to release this next week.

**Comment by samtingleff** [comment]
Reopened as this change was not yet released

**Comment by samtingleff** [comment]
released today. @pariz can you validate?

**Comment by samtingleff** [comment]
Assuming this is fixed. @pariz please reopen if not.
