### ISSUE TITLE
Production deployment prerequisites

### ISSUE THREAD

**Issue by samtingleff** [digi-trust/cmp#19]
- branching/release plan in place
  - proposal: http://www.nomachetejuggling.com/assets/three-flow.png
- separate hostnames for dev/test and production
  - proposal: cmp-origin-{branch}.digitru.st/ with production CDN at cmp.digitru.st
- monitoring
  - minimum: directly monitor production assets
  - ideal: transactional monitoring 
- SSL cert in production
- CDN configuration
  - geoip header working
  - cache html content
  - cache headers
  - send cache content on origin failures
  - CORS headers

**Comment by SupahNickie** [comment]
@samtingleff looks good to me 👍 When did we want to start this sort of branching cycle? It's probably going to become more important with Jurij on board now and any other devs that we add.

**Comment by samtingleff** [comment]
> When did we want to start this sort of branching cycle?

right now! :)

**Comment by samtingleff** [comment]
I've created `candidate` and `release` branches.

**Comment by SupahNickie** [comment]
@samtingleff and @braizhas I've created the PR to add geoip.json to the build folder during webpack build here: https://github.com/digi-trust/cmp/pull/65

**Comment by samtingleff** [comment]
Thanks @SupahNickie. I've merged #65 into master/candidate/release.
