### ISSUE TITLE
Publisher Configuration: Support Global Consent 

### ISSUE THREAD

**Issue by anissaconnor** [digi-trust/cmp#22]
Summary:
Global consent is where publishers collect consent for a set of purposes and features on behalf of their vendor partners. This consent applies to the user when they are on the publisher's site and on other sites across the net that also opt for global consent. Global consent is stored in consensu.org

Acceptance Criteria:
As a publisher, I should be able to configure the CMP for global consent

Details:
If the user has disabled third party cookies or the browser does not support third party cookies, global consent should fallback to service specific consent (consent string is stored in the publisher domain)

**Comment by SupahNickie** [comment]
Closed in https://github.com/digi-trust/cmp/pull/63
