### ISSUE TITLE
Set DigiTrust ID for users that have consented to DigiTrust on vendor list

### ISSUE THREAD

**Issue by anissaconnor** [digi-trust/cmp#34]
The DigiTrust CMP should set DigiTrust ID as a first party cookie and in DigiTru.st domain whenever the user sees the consent window and DigiTrust has consent as a vendor. DigiTrust (vendor ID 64 on the GVL) added as a vendor on the publisher vendor whitelist by default. At a high level:
On "OK",
if consent granted for ID 64
url encode the current page url
send a redirect through https://cdn.digitru.st/prod/1.5.10/redirect.html?redirect={current_page_url}

CMP users can opt for a different CMP if they don't want to set an id that widely distributes a persistent identifier.

**Comment by samtingleff** [comment]
How I imagine this working:

On "OK",
- if consent granted for ID 64
- url encode current page url {url}
- send a redirect through
```
https://cdn.digitru.st/prod/1.5.9/redirect.html?redirect={url}
```

**Comment by samtingleff** [comment]
See https://github.com/digi-trust/cmp/pull/124

**Comment by SupahNickie** [comment]
I tested the redirect locally with an example domain set up and it made the request through to the proper configured param. The behavior of the CMP is as expected after merging https://github.com/digi-trust/cmp/pull/124
