### ISSUE TITLE
Expand definition of consent types influencing re-prompting to be more complete

### ISSUE THREAD

**Issue by anissaconnor** [digi-trust/cmp#48]
Expand the definition of the following consent types that influence reprompting:
From:
*no consent given*  - all vendors are not allowed
*some consent given* - some, but not all vendors are allowed
*full consent given* - all vendors in the list are allowed)

TO
*no consent given* - all vendors are not allowed and all data purposes are not allowed, all vendors are not allowed and some data purposes are not allowed, some vendors are allowed and all data purposes are not allowed.
*some consent given* - some vendors and some purposes, but not all are allowed
*full consent given* - all vendors and purposes in the list are allowed

**Comment by SupahNickie** [comment]
Closed for the first release; looking at vendors only (no regard for purposes yet). Will likely revisit during pubvendors.json implementation.
