### ISSUE TITLE
Translate standardised language to IAB Recommended languages

### ISSUE THREAD

**Issue by anissaconnor** [digi-trust/cmp#5]
The IAB recommends the following languages are supported:
Bulgarian, Czech, Croatian, Danish, German, Greek, English, Spanish, Estonian, Finnish, French, Hungarian, Icelandic, Irish, Italian, Lithuanian, Latvian, Malti, Dutch, Norwegian, Polish, Portuguese, Romanian, Slovak, Slovene, Swedish and Turkish

**Comment by SupahNickie** [comment]
Duplicate of https://github.com/digi-trust/cmp/issues/21
