### ISSUE TITLE
Geotargeting EU Users

### ISSUE THREAD

**Issue by hbruce27** [digi-trust/cmp#6]
Summary: 
For those publishers that don't want to show the CMP to all site visitors, we need a way of determining who to show it to based on their location data.

Acceptance Criteria:
As a publisher, I should be able to configure the CMP with the hasGlobalScope method so that the CMP is only shown to users who are in the EU

Details:
For the time being, we are going to rely on the `navigator.language` object to determine location
This will be used in conjunction with http://ut-usc.ra.linksynergy.com/gdpr

**Comment by hbruce27** [comment]
If the user's browser language is set to any of the following, we will assume that they are located in the EU and subject to GDPR.
`const EU_COUNTRY_CODES = [
"bg",
"hr",
"tr",
"cs",
"da",
"et",
"fi",
"fr",
"fr-be",
"fr-fr",
"fr-lu",
"fr-mc",
"fr-ch",
"de",
"de-at",
"de-de",
"de-li",
"de-lu",
"de-ch",
"el",
"hu",
"gd-ie",
"ga",
"it",
"it-ch",
"lv",
"lt",
"lb",
"mt",
"nl",
"nl-be",
"pl",
"pt",
"rm",
"ro",
"ro-mo",
"sk",
"sl",
"es",
"es-es",
"cy",
"sv",
"sv-fi",
"sv-sv",
"en-gb",
"en-ie",
"mo",
"ru-mo",
"eu",
"ca",
"co",
"fo",
"fy",
"fur",
"gd",
"gl",
"is",
"la",
"no",
"nb",
"nn",
"oc",
"sc",
"sb",
"hsb",
"vo",
"wa",
"ar",
"ast",
"br",
"eo"
];`

**Comment by SupahNickie** [comment]
Need to keep in mind to update the current IP Geolocation service webpage to https and update the configuration file when appropriate.

**Comment by samtingleff** [comment]
Also audit the CORS headers to see if we can remove '*'
