### ISSUE TITLE
Update UI

### ISSUE THREAD

**Issue by vytautasadform** [digi-trust/cmp#66]
Make these improvements:
https://g5mk65.axshare.com/#g=1&p=comments

Additional improvement:

- Incorporate an enable/disable all button on the partner screen (3rd screen). The group agreed that this is required given there are 180 vendors the users can make choices about.
 - On the primary screen, there are some words that if you click on them, they show additional information. Think of a way to display this information in a more user friendly way.
- Bug: if user selects a purpose and scrolls down, when user selects another purpose, user should be back to the beginning of the other purpose.

**Comment by SupahNickie** [comment]
<img width="566" alt="screen shot 2018-05-23 at 12 04 25 pm" src="https://user-images.githubusercontent.com/4782746/40445621-81190b18-5e81-11e8-99eb-5d05dde1486b.png">

@braizhas , will your UI developer please take a look at making this fit better? Thanks :)

**Comment by braizhas** [comment]
@SupahNickie , he is still working on a layout.
