### ISSUE TITLE
UX Change: Change language of 'Ok, Continue to site' button on primary consent screen

### ISSUE THREAD

**Issue by SupahNickie** [digi-trust/cmp#97]
For review by @anissaconnor @hbruce27 @vytautasadform 
From a Rakuten developer: 
>"(person) from our QA team noticed a potential issue with the CMP UI. To recreate, fire up the UI and just click OK Go to site. Browse a couple pages (or refresh current), bring up the UI again then click Learn More and turn off Purpose 1, click OK then browse a couple pages /refresh. Bring up the UI one more time and just click OK. The inactivated purposes are overwritten with consent granted. Not sure if this is expected behaviour but thought it best to check with you 1st"

When the CMP is shown, clicking OK on the intro page always defaults to consenting to all. Should that instead honor the current value of the consent found in the cookie (if one exists)?

**Comment by anissaconnor** [comment]
My expectation is that the UX should hold the user's consent preferences (i.e. reflect preferences in consent cookie - highest priority cookie - service specific>group>global) for the following reason:

- Current behaviour does not honour the promise that 'you can edit your consent preferences at anytime' given that they are not saved

**Comment by SupahNickie** [comment]
The working group has decided that the behavior of the CMP does not need to change, but that the language of the buttons should. Currently the "OK, continue to site" verbiage is too passive and should be something more along the lines of "Allow all vendors/purposes" to accurately reflect what it is they are consenting to.

**Comment by anissaconnor** [comment]
I propose 'Accept All' to keep it simple.

**Comment by hbruce27** [comment]
I prefer 'Accept and Continue', but am satisfied with 'Accept All'

**Comment by jfpsf** [comment]
Works for me

**Comment by SupahNickie** [comment]
PR open here https://github.com/digi-trust/cmp/pull/114 but we need translations for the supported languages for the phrase "accept all" to add to it.
