### ISSUE TITLE
Bug investigation - Should the CMP pass the full consent string in the metadata parameter of the __cmp(“getVendorConsents”) method

### ISSUE THREAD

**Issue by anissaconnor** [digi-trust/cmp#98]
Pubmatic is saying that the DigiTrust CMP is passing the full consent string in the metadata parameter of the __cmp(“getVendorConsents”) method.  Check the current vs expected behaviour here and fix if necessary.

**Comment by SupahNickie** [comment]
Expected behavior is a slightly trimmed down version of the consent string: https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/CMP%20JS%20API%20v1.1%20Final.md#vendorconsents-

The keys are:
```
Cookie Version
Created Timestamp
Last Updated Timestamp
Cmp Id
Cmp Version
Consent Screen
Vendor List Version
Publisher Purposes Version (for the PublisherConsent metadata only)
```
